In [2]:
import pandas as pd
import json
import requests

In [3]:
r = requests.get("https://financialmodelingprep.com/api/v3/stock/list?apikey=e411bd9e9db8094b51a796cc4a6345fc")

In [4]:
r.status_code

200

In [7]:
data = pd.DataFrame(r.json())

In [15]:
data.groupby(data['exchange']).size()

exchange
Amsterdam                   133
BATS                        142
BATS Exchange               258
Brussels                    165
Lisbon                       51
MCX                           6
NASDAQ Capital Market       878
NASDAQ Global Market        847
NYSE                        445
NYSE American               353
NYSE Arca                  1540
NYSEArca                    331
Nasdaq                     1537
Nasdaq Global Select       1504
NasdaqCM                    396
NasdaqGM                    155
NasdaqGS                    556
New York Stock Exchange    2602
Other OTC                    11
Paris                       858
Swiss                         1
Toronto                    1196
YHD                         255
dtype: int64

In [16]:
data.head()

,exchange,name,price,symbol
0,NYSE Arca,SPDR S&P 500,312.23,SPY
1,Nasdaq Global Select,Comcast Corporation Class A Common Stock,39.25,CMCSA
2,New York Stock Exchange,Kinder Morgan Inc.,15.12,KMI
3,Nasdaq Global Select,Intel Corporation,59.13,INTC
4,Nasdaq Global Select,Micron Technology Inc.,49.83,MU

In [24]:
data

,exchange,name,price,symbol
0,NYSE Arca,SPDR S&P 500,312.2300,SPY
1,Nasdaq Global Select,Comcast Corporation Class A Common Stock,39.2500,CMCSA
2,New York Stock Exchange,Kinder Morgan Inc.,15.1200,KMI
3,Nasdaq Global Select,Intel Corporation,59.1300,INTC
4,Nasdaq Global Select,Micron Technology Inc.,49.8300,MU
5,NYSE Arca,VanEck Vectors Gold Miners,36.1700,GDX
6,New York Stock Exchange,General Electric Company,6.8200,GE
7,New York Stock Exchange,Bank of America Corporation,23.2900,BAC
8,NYSE Arca,iShares MSCI Emerging Index Fund,41.3600,EEM
9,NYSE Arca,SPDR Select Sector Fund - Financial,22.9700,XLF
10,Nasdaq Global Select,Apple Inc.,364.1100,AAPL
11,Nasdaq Global Select,Microsoft Corporation,206.2600,MSFT
12,Nasdaq Global Select,Sirius XM Holdings Inc.,5.8400,SIRI
13,New York Stock Exchange,HP Inc.,17.0700,HPQ
14,New York Stock Exchange,Cemex S.A.B. de C.V. Sponsored ADR,2.8200,CX
15,NYSE Arca,iShares MSCI EAFE,61.7700,EFA
16,Nasdaq Global Select,Caesars Entertainment Corporation,12.3000,CZR
17,NASDAQ Global Market,PowerShares QQQ Trust Series 1,252.1900,QQQ
18,New York Stock Exchange,Ford Motor Company,6.0500,F
19,NASDAQ Capital Market,Advanced Micro Devices Inc.,52.3400,AMD
20,New York Stock Exchange,Snap Inc. Class A,23.2200,SNAP
21,Nasdaq Global Select,Facebook Inc.,233.4200,FB
22,New York Stock Exchange,Wells Fargo & Company,25.3400,WFC
23,New York Stock Exchange,American International Group Inc.,29.9200,AIG
24,New York Stock Exchange,AT&T Inc.,30.0800,T
25,New York Stock Exchange,Citigroup Inc.,50.5500,C
26,New York Stock Exchange,VALE S.A. American Depositary Shares Each Repr...,10.4100,VALE
27,New York Stock Exchange,Morgan Stanley,47.7900,MS
28,New York Stock Exchange,AK Steel Holding Corporation,1.5500,AKS
29,New York Stock Exchange,JP Morgan Chase & Co.,92.6600,JPM
...,...,...,...,...
14270,NasdaqGS,NaN,16.0000,FUSN
14271,NasdaqGS,NaN,4.3700,EBON
14272,NasdaqGS,NaN,7.9000,FREE
14273,NYSE,NaN,24.7000,THY
14274,NYSE,NaN,25.7400,MRSK
14275,NYSE,NaN,25.2340,VIRS
14276,NYSE,NaN,37.8500,SII
14277,NasdaqGS,NaN,25.0000,HTLFP
14278,NYSE,NaN,25.1974,AZAL
14279,NYSE,NaN,24.9300,SAK
14280,NYSE American,NaN,25.2100,AZBL
14281,NasdaqGS,NaN,6.8100,MGNI
14282,NasdaqGS,NaN,21.4900,ALTA
14283,NasdaqCM,NaN,4.0600,ADTX
14284,NasdaqGS,NaN,25.3115,SPQQ
14285,NYSE American,NaN,23.1100,KJUL
14286,NYSE,NaN,41.2284,NJUL
14287,NYSE,NaN,25.1215,JULZ
14288,MCX,NaN,197.2000,GAZP.ME
14289,MCX,NaN,210.0800,SBER.ME
14290,MCX,NaN,5416.5000,LKOH.ME
14291,MCX,NaN,80.8400,AFLT.ME
14292,MCX,NaN,4213.5000,MGNT.ME
14293,NYSE,NaN,69.4100,LMND
14294,NasdaqGS,NaN,9.8000,GIK
14295,NasdaqGS,NaN,9.2500,HOFV
14296,NasdaqGS,NaN,15.0500,IMTX
14297,NasdaqGS,NaN,1.8500,HOFVW
14298,NasdaqGS,NaN,29.7000,ACCD
14299,MCX,NaN,1754.8000,MAIL.ME